# Generated by Django 2.2.13 on 2020-07-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='thumb',
            new_name='poster',
        ),
    ]
