# Generated by Django 2.2.13 on 2020-07-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200708_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='poster',
        ),
    ]
